baseURL = "http://zucchiniy.github.io"
languageCode = "zh"
defaultContentLanguage = "zh-cn"
title = "游行侠Z"

enableRobotsTXT = true
enableEmoji = true
theme = "even"

hasCJKLanguage = true
paginate = 5

[author]
    name = "Dylan Yang"

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[[menu.main]]
    name = "首页"
    weight = 10
    idengifier = "home"
    url = "/"
[[menu.main]]
    name = "归档"
    weight = 20
    idengifier = "archives"
    url = "/post/"
[[menu.main]]
    name = "标签"
    weight = 30
    idengifier = "tags"
    url = "/tags/"
[[menu.main]]
    name = "分类"
    weight = 40
    idengifier = "categories"
    url = "/categories/"
[[menu.main]]
    name = "关于"
    weight = 50
    idengifier = "about"
    url = "/about"

[params]
    version = "3.x"
    debug = false
    since = "2015" # 站点建立时间
    archivePaginate = 50 # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
    dateFormatToUse = "2006-01-02"
    moreMeta = false # 是否显示字数统计与阅读时间
	description = "世事洞明皆学问，人情练达即文章。"

[params.reward]                                         # 文章打赏
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
    alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

  [params.social]                                         # 社交链接
    a-email = "mailto:banshiliuli1990@sina.com"
    b-github = "https://github.com/ZucchiniY"