baseURL = "http://zucchiniy.github.io"
languageCode = "zh"
defaultContentLanguage = "zh-cn"
title = "游行侠Z"

pygmentsUseClasses = false
uglyURLs = true
publicshdir = "public"

theme = "jane"

hasCJKLanguage = true
paginate = 5
rssLimit = 20
metaDataFormat = "YAML"

[author]
    description = "一名伪程序员"
    name = "Dylan Yang"

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[taxonomies]
    tag = "tags"
    category = "categories"

[permalinks]
    post = "/blog/:year/:slug"
    resource = "/resource/:title"

[[menu.main]]
    name = "首页"
    weight = 10
    idengifier = "home"
    url = "/"
[[menu.main]]
    name = "目录"
    weight = 20
    idengifier = "archives"
    url = "/post.html"
#[[menu.main]]
#    name = "标签"
#    weight = 30
#    idengifier = "tags"
#    url = "/tags.html"
[[menu.main]]
    name = "分类"
    weight = 40
    idengifier = "categories"
    url = "/categories.html"
[[menu.main]]
    name = "关于"
    weight = 50
    idengifier = "about"
    url = "/about.html"

[params]
    debug = false
    since = "2015" # 站点建立时间
    archive-paginate = 10 # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
    dateFormatToUse = "2006-01-02"
    moreMeta = true # 是否显示字数统计与阅读时间
	description = "世事洞明皆学问，人情练达即文章。"
    homeFullContent = false
    rssFullContent = true
    uglyURLs = true

[params.reward]                                         # 文章打赏
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
    alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

[params.social]                                         # 社交链接
    a-email = "mailto:banshiliuli1990@sina.com"
    b-github = "https://github.com/ZucchiniY"
