baseURL = "http://zucchiniy.github.io"
languageCode = "zh"
defaultContentLanguage = "zh-cn"
title = "游行侠Z"

theme = "paladin"

hasCJKLanguage = true
paginate = 5
rssLimit = 20
metaDataFormat = "YAML"

[author]
    description = "一名伪程序员"
    name = "Dylan Yang"

[[menu.main]]
    name = "HOME"
    weight = 10
    idengifier = "home"
    url = "/"
[[menu.main]]
    name = "ARCHIVE"
    weight = 20
    idengifier = "archives"
    url = "/post"
[[menu.main]]
    name = "ABOUT"
    weight = 50
    idengifier = "about"
    url = "/about"

[params]
    since = "2015" # 站点建立时间
    archive-paginate = 10 # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
    dateFormatToUse = "January 02,2006"
    footer = "[Hugo](https://gohugo.io) &copy; [Paladin](https://github.com/ZCodingTime/hugo-theme-paladin) [DylanYang](https://zucchiniy.github.io) 2018"
    description = "世事洞明皆学问，人情练达即文章。"
    keywords = ["coding","learning"]

[permalinks]
	post = "/:slug"

[params.social]                                         # 社交链接
    a-email = "mailto:banshiliuli1990@sina.com"
    b-github = "https://github.com/ZucchiniY"
